[package]
name = "hab"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
build = "../build.rs"
workspace = "../../"

[[bin]]
name = "hab"
doc = false

[dependencies]
ansi_term = "*"
env_logger = "*"
hyper = "*"
handlebars = { version = "*", features = ["serde_type", "partial4"], default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
pbr = "*"
regex = "*"
retry = "*"
serde = "*"
serde_derive = "*"
toml = { version = "*", features = ["serde"], default-features = false, git = "https://github.com/alexcrichton/toml-rs" , rev = "d39c3f7b3ec95cb3cc1e579d7d747206c66aab74" }
url = "*"
walkdir = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_common]
path = "../common"

[dependencies.habitat_depot_client]
path = "../builder-depot-client"

[dependencies.habitat_http_client]
path = "../http-client"

[dependencies.uuid]
version = "*"
features = ["v4"]

[features]
functional = []
