[package]
name = "hab-spider"
version = "0.1.0"
authors = ["Salim Alam <salam@chef.io>"]
workspace = "../../"

[dependencies]
log = "*"
env_logger = "*"
petgraph = "*"
walkdir = "*"
libarchive = "*"
time = "*"
clap = "2"
protobuf = "*"
postgres = "*"
r2d2 = "*"

[dependencies.habitat_core]
path = "../core"

[dependencies.builder_core]
path = "../builder-core"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[dependencies.habitat_builder_db]
path = "../builder-db"

[dependencies.habitat_net]
path = "../net"

[build-dependencies]
pkg-config = "0.3"
